2020-05-19 22:05:02,387 - root - INFO - Started
2020-05-19 22:05:02,652 - root - ERROR - Traceback (most recent call last):
  File "train/train_wsi_on_1x1_pretrained.py", line 133, in <module>
    fast_dev_run=False, num_sanity_val_steps=0)
  File "/home/ruslan/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 438, in __init__
    self.data_parallel_device_ids = parse_gpu_ids(self.gpus)
  File "/home/ruslan/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 712, in parse_gpu_ids
    gpus = sanitize_gpu_ids(gpus)
  File "/home/ruslan/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 678, in sanitize_gpu_ids
    """)
pytorch_lightning.utilities.exceptions.MisconfigurationException: 
                You requested GPUs: [0]
                But your machine only has: []
            

